question_data = [
	{"category": "General Knowledge",
	 "type": "multiple",
	 "difficulty": "hard",
	 "question": "Electronic music producer Kygo&#039;s popularity skyrocketed after a certain remix. Which song did he remix?",
	 "correct_answer": "Ed Sheeran - I See Fire",
	 "incorrect_answers": ["Marvin Gaye - Sexual Healing", "Coldplay - Midnight", "a-ha - Take On Me"]},
	{"category": "History", "type": "multiple", "difficulty": "hard",
	 "question": "Which naval battle was considered the turning point of the Pacific Ocean Theater during World War 2?",
	 "correct_answer": "Battle of Midway",
	 "incorrect_answers": ["Attack on Truk Island", "Attack on Pearl Harbor", "Battle of the Coral Sea"]},
	{"category": "Entertainment: Board Games", "type": "multiple", "difficulty": "medium",
	 "question": "Who is the main character in the VHS tape included in the board game Nightmare?",
	 "correct_answer": "The Gatekeeper", "incorrect_answers": ["The Kryptkeeper", "The Monster", "The Nightmare"]},
	{"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "medium",
	 "question": "The creator of the Touhou Project series is:", "correct_answer": "ZUN",
	 "incorrect_answers": ["SUN", "RUN", "PUN"]},
	{"category": "Geography", "type": "boolean", "difficulty": "easy",
	 "question": "Toronto is the capital city of the North American country of Canada.",
	 "correct_answer": "False", "incorrect_answers": ["True"]},
	{"category": "Entertainment: Music", "type": "multiple", "difficulty": "medium",
	 "question": "The song &quot;Feel Good Inc.&quot; by British band Gorillaz features which hip hop group?",
	 "correct_answer": "De La Soul", "incorrect_answers": ["Public Enemy", "OutKast", "Cypress Hill"]},
	{"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "easy",
	 "question": "In which mall does &quot;Dead Rising&quot; take place?",
	 "correct_answer": "Willamette Parkview Mall",
	 "incorrect_answers": ["Liberty Mall", "Twin Pines Mall", "Central Square Shopping Center"]},
	{"category": "Science & Nature", "type": "multiple", "difficulty": "hard",
	 "question": "Coulrophobia is the irrational fear of what?", "correct_answer": "Clowns",
	 "incorrect_answers": ["Cemeteries", "Needles", "Tunnels"]},
	{"category": "Geography", "type": "multiple", "difficulty": "easy",
	 "question": "The longest shared border in the world can be found between which two nations?",
	 "correct_answer": "Canada and the United States",
	 "incorrect_answers": ["Chile and Argentina", "Russia and China", "India and Pakistan"]},
	{"category": "Science & Nature", "type": "multiple", "difficulty": "hard",
	 "question": "Which major extinction event was caused by an asteroid collision and eliminated the majority of non-avian dinosaurs?",
	 "correct_answer": "Cretaceous-Paleogene",
	 "incorrect_answers": ["Triassic&ndash;Jurassic", "Permian&ndash;Triassic", "Ordovician&ndash;Silurian"]}]
